db.libros.insertMany([
    {Título: "Secuestrado",
    Editorial: "Alba Editorial",
    Autor: "Robert Louis Stevenson",
    Fecha: "19-09-2018",
    NºPáginas: 280,
    Dimensiones_mm: [210, 140]},

    {Título: "Línea de fuego",
    Editorial: "Alfaguara",
    Autor: "Arturo Pérez Reverte",
    Fecha: "06-10-2020",
    NºPáginas: 688,
    Dimensiones_mm: [248, 162]},

    {Título: "Las tinieblas y el alba",
    Editorial: "Plaza & Janes",
    Autor: "Ken Follett",
    Fecha: "15-09-2020",
    NºPáginas: 936,
    Dimensiones_mm: [237, 164]},

    {Título: "La vida contada por un sapiens a un neandertal",
    Editorial: "Alfaguara",
    Autor: "Juan José Millas",
    Fecha: "23-09-2020",
    NºPáginas: 224,
    Dimensiones_mm: [240, 154]},

    {Título: "Dime qué comes y te diré qué bacterias tienes. El intestino, nuestro segundo cerebro",
    Editorial: "Grijalbo Ilustrados",
    Autor: "Blanca García",
    Fecha: "08-10-2020",
    NºPáginas: 272,
    Dimensiones_mm: [240, 154]},

    {Título: "¿A qué estás esperando?",
    Editorial: "Esencia",
    Autor: "Megan Maxwell",
    Fecha: "29-10-2020",
    NºPáginas: 672,
    Dimensiones_mm: [240, 154]},

    {Título: "La buena suerte",
    Editorial: "Alfaguara",
    Autor: "Rosa Montero",
    Fecha: "27-08-2020",
    NºPáginas: 328,
    Dimensiones_mm: [240, 154]},

    {Título: "Los tiempos del odio",
    Editorial: "Booket",
    Autor: "Rosa Montero",
    Fecha: "10-03-2020",
    NºPáginas: 400,
    Dimensiones_mm: [190, 125]},

    {Título: "La ridícula idea de no volver a verte",
    Editorial: "Booket",
    Autor: "Rosa Montero",
    Fecha: "03-06-2014",
    NºPáginas: 240,
    Dimensiones_mm: [190, 125]},

    {Título: "La carne",
    Editorial: "Debolsillo",
    Autor: "Rosa Montero",
    Fecha: "07-09-2017",
    NºPáginas: 240,
    Dimensiones_mm: [240, 154]},

    {Título: "Sidi",
    Editorial: "Alfaguara",
    Autor: "Arturo Pérez Reverte",
    Fecha: "18-09-2019",
    NºPáginas: 376,
    Dimensiones_mm: [240, 154]},

    {Título: "La chica de nieve",
    Editorial: "Suma",
    Autor: "Javier Castillo",
    Fecha: "12-03-2020",
    NºPáginas: 512,
    Dimensiones_mm: [230, 155]},

    {Título: "El día que se perdió la cordura",
    Editorial: "Debolsillo",
    Autor: "Javier Castillo",
    Fecha: "09-05-2019",
    NºPáginas: 456,
    Dimensiones_mm: [190, 125]},

    {Título: "El día que se perdió el amor",
    Editorial: "Debolsillo",
    Autor: "Javier Castillo",
    Fecha: "09-05-2019",
    NºPáginas: 432,
    Dimensiones_mm: [190, 125]},

    {Título: "Todo lo que sucedió con Miranda Huff",
    Editorial: "Suma",
    Autor: "Javier Castillo",
    Fecha: "14-03-2019",
    NºPáginas: 448,
    Dimensiones_mm: [230, 153]},

    {Título: "Diario de Anne Frank",
    Editorial: "Debolsillo",
    Autor: "Anne Frank",
    Fecha: "08-01-2018",
    NºPáginas: 388,
    Dimensiones_mm: [190, 124]}
])